# version: "3.9" (auschecken warum unnötig?)
# docker compose version Runner v5.1.1

services:
  frontend:
    build:
      context: ./FE
    container_name: hospitality-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - hospitality-net

  caddy:
    image: caddy:2
    container_name: hospitality-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - hospitality-net

networks:
  hospitality-net:

volumes:
  caddy_data:
  caddy_config: